/**
 * @fileoverview Message info type from OpenCode SDK.
 */

import type { MessageSummary } from "./MessageSummary"

/**
 * Information about a message in the conversation.
 */
export interface MessageInfo {
  /** The role of the message sender */
  role: "user" | "assistant"

  /** Optional summary generated by the LLM */
  summary?: MessageSummary
}
