/**
 * @fileoverview Message part type from OpenCode SDK.
 */

/**
 * A part of a message (text, file, tool call, etc.).
 */
export interface MessagePart {
  /** The type of the part (e.g., "text", "tool", "file") */
  type: string

  /** Text content for text parts */
  text?: string

  /**
   * Whether this part was synthetically generated by OpenCode.
   *
   * @remarks
   * OpenCode creates synthetic text parts for file contents, MCP resources,
   * and other system-injected content. These should be excluded from
   * ticket extraction as they may contain example patterns from docs.
   */
  synthetic?: boolean
}
